package com.example.demo.car;

import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.time.LocalDate;
import java.time.Month;
import java.util.List;

@Configuration
public class CarConfig {

    @Bean
    CommandLineRunner commandLineRunner(CarRepository carRepository){
        return args -> {
            Car audi_a3 = new Car(
                    //ID gets autogenerated
                    "Audi",
                    "A3 8PA",
                    150.0,
                    LocalDate.of(2012, Month.APRIL, 11)
            );

            Car audi_rs3 = new Car(
                    "Audi",
                    "RS3 8Y",
                    400.0,
                    LocalDate.of(2022, Month.APRIL, 11)
            );

            carRepository.saveAll(List.of(audi_a3, audi_rs3));
        };
    }
}
